#!/usr/bin/env python3
import sys, requests

if len(sys.argv) < 2:
    print("⛔ Usage: weatherly <city>")
    sys.exit(1)

city = " ".join(sys.argv[1:])
url = f"https://wttr.in/{city}?format=3"

try:
    r = requests.get(url)
    print(r.text)
except:
    print("💥 Failed to fetch weather.")
